# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-06 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.IntegerField(choices=[(0, 'Hamburger'), (1, 'Pancake')], default=0)),
                ('ingridients', models.CharField(max_length=1024)),
            ],
        ),
    ]
