# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-06 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese', models.IntegerField(default=0)),
                ('ham', models.IntegerField(default=0)),
                ('onion', models.IntegerField(default=0)),
                ('bread', models.IntegerField(default=0)),
                ('ketchup', models.IntegerField(default=0)),
                ('milk', models.IntegerField(default=0)),
                ('butter', models.IntegerField(default=0)),
                ('honey', models.IntegerField(default=0)),
                ('eggs', models.IntegerField(default=0)),
            ],
        ),
    ]
