# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-06 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_ingridients'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backtest_type', models.CharField(choices=[('moving_averages', 'Moving Averages'), ('bollinger_bands', 'Bollinger Bands')], default='moving_averages', max_length=1024)),
                ('backtest_details', models.CharField(max_length=1024)),
            ],
        ),
        migrations.DeleteModel(
            name='Ingridients',
        ),
    ]
