# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-09 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20190206_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestmodel',
            name='pairChosen',
            field=models.CharField(choices=[('ETHUSDT', 'USDT_ETH'), ('others', 'Others')], default='ETHUSDT', max_length=1024),
        ),
        migrations.AddField(
            model_name='backtestmodel',
            name='periodChosen',
            field=models.CharField(choices=[('KLINE_INTERVAL_4HOUR', '4h'), ('others', 'Others')], default='KLINE_INTERVAL_4HOUR', max_length=1024),
        ),
    ]
